### ISSUE TITLE
Link a la Wallet roto

### ISSUE THREAD

**Issue by eliooses** [bitex-la/pesodigital_website#1]
En: http://pesodigital.info/plan.html#implementacion

El link "Para recibirlos solo necesitas crear una billetera en CoinPrism." (https://www.coinprism.com/wallet)
arroja un 404:

> Not found
> Sorry, we couldn't find the page you were looking for.

![image](https://cloud.githubusercontent.com/assets/5062034/22866176/671a33bc-f150-11e6-9ecd-ee5b22e7b580.png)

**Comment by nubis** [comment]
Ahí está. Gracias!
